-- Generated by scripts/convert-mysql-migrations-to-postgresql.mjs
-- Run once in a new CloudBase PostgreSQL environment.

CREATE TABLE IF NOT EXISTS user_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_no VARCHAR(64) DEFAULT NULL,
  openid VARCHAR(128) DEFAULT NULL,
  unionid VARCHAR(128) DEFAULT NULL,
  nickname VARCHAR(100) NOT NULL DEFAULT '微信用户',
  real_name VARCHAR(50) DEFAULT NULL,
  mobile VARCHAR(20) DEFAULT NULL,
  avatar_url VARCHAR(255) DEFAULT NULL,
  user_status SMALLINT NOT NULL DEFAULT 1,
  register_source VARCHAR(20) NOT NULL DEFAULT 'miniapp',
  is_member SMALLINT NOT NULL DEFAULT 0,
  member_level VARCHAR(30) NOT NULL DEFAULT 'normal',
  member_since_time TIMESTAMP DEFAULT NULL,
  last_login_time TIMESTAMP DEFAULT NULL,
  last_consume_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_user_no UNIQUE (user_no),
  CONSTRAINT uk_openid UNIQUE (openid),
  CONSTRAINT uk_unionid UNIQUE (unionid),
  CONSTRAINT uk_mobile UNIQUE (mobile)
);

CREATE INDEX IF NOT EXISTS user_info__idx_user_status ON user_info (user_status);

CREATE INDEX IF NOT EXISTS user_info__idx_is_member ON user_info (is_member);

CREATE INDEX IF NOT EXISTS user_info__idx_member_level ON user_info (member_level);

CREATE INDEX IF NOT EXISTS user_info__idx_created_at ON user_info (created_at);

CREATE TABLE IF NOT EXISTS user_membership_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  before_is_member SMALLINT NOT NULL DEFAULT 0,
  after_is_member SMALLINT NOT NULL DEFAULT 0,
  before_member_level VARCHAR(30) DEFAULT NULL,
  after_member_level VARCHAR(30) DEFAULT NULL,
  change_type VARCHAR(30) NOT NULL,
  change_reason VARCHAR(255) DEFAULT NULL,
  operator_type VARCHAR(20) NOT NULL DEFAULT 'system',
  operator_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS user_membership_log__idx_user_id ON user_membership_log (user_id);

CREATE INDEX IF NOT EXISTS user_membership_log__idx_change_type ON user_membership_log (change_type);

CREATE INDEX IF NOT EXISTS user_membership_log__idx_created_at ON user_membership_log (created_at);

CREATE TABLE IF NOT EXISTS user_vehicle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  plate_no VARCHAR(20) DEFAULT NULL,
  vehicle_brand VARCHAR(50) DEFAULT NULL,
  vehicle_model VARCHAR(100) DEFAULT NULL,
  vehicle_color VARCHAR(30) DEFAULT NULL,
  is_default SMALLINT NOT NULL DEFAULT 0,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS user_vehicle__idx_user_id ON user_vehicle (user_id);

CREATE INDEX IF NOT EXISTS user_vehicle__idx_plate_no ON user_vehicle (plate_no);

CREATE TABLE IF NOT EXISTS store (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  store_code VARCHAR(64) NOT NULL,
  store_name VARCHAR(100) NOT NULL,
  store_status SMALLINT NOT NULL DEFAULT 1,
  province VARCHAR(50) DEFAULT NULL,
  city VARCHAR(50) DEFAULT NULL,
  district VARCHAR(50) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  longitude DECIMAL(10,6) DEFAULT NULL,
  latitude DECIMAL(10,6) DEFAULT NULL,
  contact_name VARCHAR(50) DEFAULT NULL,
  contact_phone VARCHAR(30) DEFAULT NULL,
  business_hours VARCHAR(100) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_store_code UNIQUE (store_code)
);

CREATE INDEX IF NOT EXISTS store__idx_store_status ON store (store_status);

CREATE TABLE IF NOT EXISTS store_bay (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  store_id BIGINT NOT NULL,
  bay_code VARCHAR(64) NOT NULL,
  bay_name VARCHAR(100) NOT NULL,
  bay_status VARCHAR(20) NOT NULL DEFAULT 'idle',
  sort_no INT NOT NULL DEFAULT 0,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_store_bay_code UNIQUE (store_id, bay_code)
);

CREATE INDEX IF NOT EXISTS store_bay__idx_store_id ON store_bay (store_id);

CREATE INDEX IF NOT EXISTS store_bay__idx_bay_status ON store_bay (bay_status);

CREATE TABLE IF NOT EXISTS device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_code VARCHAR(64) NOT NULL,
  store_id BIGINT NOT NULL,
  bay_id BIGINT DEFAULT NULL,
  device_type VARCHAR(30) NOT NULL DEFAULT 'washer',
  device_name VARCHAR(100) DEFAULT NULL,
  device_status VARCHAR(20) NOT NULL DEFAULT 'offline',
  protocol_type VARCHAR(30) DEFAULT NULL,
  firmware_version VARCHAR(50) DEFAULT NULL,
  last_heartbeat_time TIMESTAMP DEFAULT NULL,
  last_online_time TIMESTAMP DEFAULT NULL,
  install_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_device_code UNIQUE (device_code)
);

CREATE INDEX IF NOT EXISTS device__idx_store_id ON device (store_id);

CREATE INDEX IF NOT EXISTS device__idx_bay_id ON device (bay_id);

CREATE INDEX IF NOT EXISTS device__idx_device_status ON device (device_status);

CREATE TABLE IF NOT EXISTS device_heartbeat_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_id BIGINT NOT NULL,
  device_code VARCHAR(64) NOT NULL,
  heartbeat_time TIMESTAMP NOT NULL,
  device_status VARCHAR(20) DEFAULT NULL,
  payload TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS device_heartbeat_log__idx_device_id ON device_heartbeat_log (device_id);

CREATE INDEX IF NOT EXISTS device_heartbeat_log__idx_device_code ON device_heartbeat_log (device_code);

CREATE INDEX IF NOT EXISTS device_heartbeat_log__idx_heartbeat_time ON device_heartbeat_log (heartbeat_time);

CREATE TABLE IF NOT EXISTS device_command_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  command_no VARCHAR(64) NOT NULL,
  device_id BIGINT NOT NULL,
  device_code VARCHAR(64) NOT NULL,
  order_id BIGINT DEFAULT NULL,
  order_no VARCHAR(64) DEFAULT NULL,
  command_type VARCHAR(30) NOT NULL,
  request_payload TEXT DEFAULT NULL,
  response_payload TEXT DEFAULT NULL,
  command_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  request_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  response_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_command_no UNIQUE (command_no)
);

CREATE INDEX IF NOT EXISTS device_command_log__idx_device_id ON device_command_log (device_id);

CREATE INDEX IF NOT EXISTS device_command_log__idx_order_id ON device_command_log (order_id);

CREATE INDEX IF NOT EXISTS device_command_log__idx_command_type ON device_command_log (command_type);

CREATE INDEX IF NOT EXISTS device_command_log__idx_command_status ON device_command_log (command_status);

CREATE TABLE IF NOT EXISTS pricing_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  store_id BIGINT NOT NULL,
  rule_name VARCHAR(100) NOT NULL,
  member_price_enabled SMALLINT NOT NULL DEFAULT 1,
  free_minutes INT NOT NULL DEFAULT 0,
  first_period_minutes INT NOT NULL DEFAULT 0,
  first_period_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  extra_price_per_minute DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  member_first_period_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  member_extra_price_per_minute DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  first_period_discount_limit_type VARCHAR(30) NOT NULL DEFAULT 'once_per_day',
  is_default SMALLINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS pricing_rule__idx_store_id ON pricing_rule (store_id);

CREATE INDEX IF NOT EXISTS pricing_rule__idx_status ON pricing_rule (status);

CREATE TABLE IF NOT EXISTS user_daily_discount_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  discount_date DATE NOT NULL,
  discount_type VARCHAR(30) NOT NULL,
  store_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_user_date_type UNIQUE (user_id, discount_date, discount_type)
);

CREATE INDEX IF NOT EXISTS user_daily_discount_record__idx_store_id ON user_daily_discount_record (store_id);

CREATE INDEX IF NOT EXISTS user_daily_discount_record__idx_order_id ON user_daily_discount_record (order_id);

CREATE INDEX IF NOT EXISTS user_daily_discount_record__idx_discount_date ON user_daily_discount_record (discount_date);

CREATE TABLE IF NOT EXISTS user_store_wallet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  principal_balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  gift_balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_recharge_principal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_recharge_gift DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_consume_principal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_consume_gift DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_refund_principal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  status SMALLINT NOT NULL DEFAULT 1,
  version INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_user_store UNIQUE (user_id, store_id)
);

CREATE INDEX IF NOT EXISTS user_store_wallet__idx_user_id ON user_store_wallet (user_id);

CREATE INDEX IF NOT EXISTS user_store_wallet__idx_store_id ON user_store_wallet (store_id);

CREATE INDEX IF NOT EXISTS user_store_wallet__idx_status ON user_store_wallet (status);

CREATE TABLE IF NOT EXISTS wallet_transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  transaction_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  biz_type VARCHAR(30) NOT NULL,
  amount_type VARCHAR(20) NOT NULL,
  change_type VARCHAR(10) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  balance_before DECIMAL(10,2) NOT NULL,
  balance_after DECIMAL(10,2) NOT NULL,
  related_order_id BIGINT DEFAULT NULL,
  related_order_no VARCHAR(64) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_transaction_no UNIQUE (transaction_no)
);

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_user_id ON wallet_transaction (user_id);

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_store_id ON wallet_transaction (store_id);

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_related_order_id ON wallet_transaction (related_order_id);

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_biz_type ON wallet_transaction (biz_type);

CREATE TABLE IF NOT EXISTS recharge_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recharge_order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  principal_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  gift_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  pay_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  pay_channel VARCHAR(30) DEFAULT NULL,
  pay_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  pay_time TIMESTAMP DEFAULT NULL,
  third_party_trade_no VARCHAR(64) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_recharge_order_no UNIQUE (recharge_order_no)
);

CREATE INDEX IF NOT EXISTS recharge_order__idx_user_id ON recharge_order (user_id);

CREATE INDEX IF NOT EXISTS recharge_order__idx_store_id ON recharge_order (store_id);

CREATE INDEX IF NOT EXISTS recharge_order__idx_pay_status ON recharge_order (pay_status);

CREATE TABLE IF NOT EXISTS card_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  store_id BIGINT NOT NULL,
  card_name VARCHAR(100) NOT NULL,
  card_type VARCHAR(20) NOT NULL,
  total_times INT NOT NULL,
  sale_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  valid_days INT DEFAULT NULL,
  is_new_user_only SMALLINT NOT NULL DEFAULT 0,
  purchase_limit INT NOT NULL DEFAULT 1,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS card_product__idx_store_id ON card_product (store_id);

CREATE INDEX IF NOT EXISTS card_product__idx_card_type ON card_product (card_type);

CREATE INDEX IF NOT EXISTS card_product__idx_status ON card_product (status);

CREATE TABLE IF NOT EXISTS card_purchase_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  purchase_order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  card_product_id BIGINT NOT NULL,
  card_type VARCHAR(20) NOT NULL,
  source_channel VARCHAR(20) NOT NULL,
  buy_count INT NOT NULL DEFAULT 1,
  pay_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  pay_status VARCHAR(20) NOT NULL DEFAULT 'paid',
  purchase_time TIMESTAMP NOT NULL,
  external_order_no VARCHAR(64) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_purchase_order_no UNIQUE (purchase_order_no)
);

CREATE INDEX IF NOT EXISTS card_purchase_order__idx_user_id ON card_purchase_order (user_id);

CREATE INDEX IF NOT EXISTS card_purchase_order__idx_store_id ON card_purchase_order (store_id);

CREATE INDEX IF NOT EXISTS card_purchase_order__idx_card_product_id ON card_purchase_order (card_product_id);

CREATE INDEX IF NOT EXISTS card_purchase_order__idx_source_channel ON card_purchase_order (source_channel);

CREATE TABLE IF NOT EXISTS user_card (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  card_product_id BIGINT NOT NULL,
  card_type VARCHAR(20) NOT NULL,
  source_channel VARCHAR(20) NOT NULL,
  card_no VARCHAR(64) NOT NULL,
  total_times INT NOT NULL,
  used_times INT NOT NULL DEFAULT 0,
  remaining_times INT NOT NULL,
  purchase_time TIMESTAMP NOT NULL,
  effective_time TIMESTAMP DEFAULT NULL,
  expire_time TIMESTAMP DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  external_order_no VARCHAR(64) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_card_no UNIQUE (card_no)
);

CREATE INDEX IF NOT EXISTS user_card__idx_user_id ON user_card (user_id);

CREATE INDEX IF NOT EXISTS user_card__idx_store_id ON user_card (store_id);

CREATE INDEX IF NOT EXISTS user_card__idx_card_product_id ON user_card (card_product_id);

CREATE INDEX IF NOT EXISTS user_card__idx_status ON user_card (status);

CREATE TABLE IF NOT EXISTS card_usage_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  usage_no VARCHAR(64) NOT NULL,
  user_card_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  order_id BIGINT DEFAULT NULL,
  order_no VARCHAR(64) DEFAULT NULL,
  used_times INT NOT NULL DEFAULT 1,
  usage_time TIMESTAMP NOT NULL,
  operator_type VARCHAR(20) NOT NULL DEFAULT 'system',
  operator_id BIGINT DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_usage_no UNIQUE (usage_no)
);

CREATE INDEX IF NOT EXISTS card_usage_record__idx_user_card_id ON card_usage_record (user_card_id);

CREATE INDEX IF NOT EXISTS card_usage_record__idx_user_id ON card_usage_record (user_id);

CREATE INDEX IF NOT EXISTS card_usage_record__idx_store_id ON card_usage_record (store_id);

CREATE INDEX IF NOT EXISTS card_usage_record__idx_order_id ON card_usage_record (order_id);

CREATE TABLE IF NOT EXISTS wash_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  bay_id BIGINT DEFAULT NULL,
  device_id BIGINT DEFAULT NULL,
  pricing_rule_id BIGINT DEFAULT NULL,
  order_source VARCHAR(20) NOT NULL DEFAULT 'miniapp',
  order_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  device_status_snapshot VARCHAR(20) DEFAULT NULL,
  pay_mode VARCHAR(20) NOT NULL DEFAULT 'wallet',
  card_usage_id BIGINT DEFAULT NULL,
  card_deduct_times INT NOT NULL DEFAULT 0,
  estimated_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  final_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  paid_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  refund_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  is_first_period_discount_used SMALLINT NOT NULL DEFAULT 0,
  first_period_discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  start_command_no VARCHAR(64) DEFAULT NULL,
  pause_command_no VARCHAR(64) DEFAULT NULL,
  stop_command_no VARCHAR(64) DEFAULT NULL,
  cancel_command_no VARCHAR(64) DEFAULT NULL,
  start_time TIMESTAMP DEFAULT NULL,
  pause_time TIMESTAMP DEFAULT NULL,
  end_time TIMESTAMP DEFAULT NULL,
  cancel_time TIMESTAMP DEFAULT NULL,
  settle_time TIMESTAMP DEFAULT NULL,
  abnormal_reason VARCHAR(255) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_order_no UNIQUE (order_no)
);

CREATE INDEX IF NOT EXISTS wash_order__idx_user_id ON wash_order (user_id);

CREATE INDEX IF NOT EXISTS wash_order__idx_store_id ON wash_order (store_id);

CREATE INDEX IF NOT EXISTS wash_order__idx_bay_id ON wash_order (bay_id);

CREATE INDEX IF NOT EXISTS wash_order__idx_device_id ON wash_order (device_id);

CREATE INDEX IF NOT EXISTS wash_order__idx_order_status ON wash_order (order_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_pay_mode ON wash_order (pay_mode);

CREATE TABLE IF NOT EXISTS wash_order_status_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  from_status VARCHAR(20) DEFAULT NULL,
  to_status VARCHAR(20) NOT NULL,
  action_type VARCHAR(30) NOT NULL,
  operator_type VARCHAR(20) NOT NULL DEFAULT 'system',
  operator_id BIGINT DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS wash_order_status_log__idx_order_id ON wash_order_status_log (order_id);

CREATE INDEX IF NOT EXISTS wash_order_status_log__idx_order_no ON wash_order_status_log (order_no);

CREATE INDEX IF NOT EXISTS wash_order_status_log__idx_to_status ON wash_order_status_log (to_status);

CREATE TABLE IF NOT EXISTS wash_order_payment_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  consume_store_id BIGINT NOT NULL,
  source_type VARCHAR(20) NOT NULL,
  source_store_id BIGINT DEFAULT NULL,
  amount_type VARCHAR(20) DEFAULT NULL,
  user_card_id BIGINT DEFAULT NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  deduct_times INT NOT NULL DEFAULT 0,
  refunded_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_order_id ON wash_order_payment_detail (order_id);

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_order_no ON wash_order_payment_detail (order_no);

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_user_id ON wash_order_payment_detail (user_id);

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_consume_store_id ON wash_order_payment_detail (consume_store_id);

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_source_type ON wash_order_payment_detail (source_type);

CREATE TABLE IF NOT EXISTS refund_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  refund_order_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  refund_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  refund_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  refund_reason VARCHAR(255) DEFAULT NULL,
  refund_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_refund_order_no UNIQUE (refund_order_no)
);

CREATE INDEX IF NOT EXISTS refund_order__idx_order_id ON refund_order (order_id);

CREATE INDEX IF NOT EXISTS refund_order__idx_user_id ON refund_order (user_id);

CREATE INDEX IF NOT EXISTS refund_order__idx_store_id ON refund_order (store_id);

CREATE INDEX IF NOT EXISTS refund_order__idx_refund_status ON refund_order (refund_status);

CREATE TABLE IF NOT EXISTS store_settlement_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  from_store_id BIGINT NOT NULL,
  to_store_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  payment_detail_id BIGINT NOT NULL,
  principal_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  refund_adjust_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  biz_date DATE NOT NULL,
  detail_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_from_store_id ON store_settlement_detail (from_store_id);

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_to_store_id ON store_settlement_detail (to_store_id);

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_order_id ON store_settlement_detail (order_id);

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_payment_detail_id ON store_settlement_detail (payment_detail_id);

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_biz_date ON store_settlement_detail (biz_date);

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_detail_status ON store_settlement_detail (detail_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_device_status ON wash_order (device_id, order_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_bay_status ON wash_order (bay_id, order_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_user_status ON wash_order (user_id, order_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_device_status ON wash_order (device_id, order_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_bay_status ON wash_order (bay_id, order_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_user_status ON wash_order (user_id, order_status);

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_user_created_at ON wallet_transaction (user_id, created_at);

CREATE INDEX IF NOT EXISTS device_heartbeat_log__idx_device_created_at ON device_heartbeat_log (device_id, created_at);

CREATE INDEX IF NOT EXISTS device_command_log__idx_device_request_time ON device_command_log (device_id, request_time);

ALTER TABLE user_store_wallet ALTER COLUMN principal_balance TYPE DECIMAL(18,2);

ALTER TABLE user_store_wallet ALTER COLUMN principal_balance SET DEFAULT 0.00;

ALTER TABLE user_store_wallet ALTER COLUMN principal_balance SET NOT NULL;

ALTER TABLE user_store_wallet ALTER COLUMN gift_balance TYPE DECIMAL(18,2);

ALTER TABLE user_store_wallet ALTER COLUMN gift_balance SET DEFAULT 0.00;

ALTER TABLE user_store_wallet ALTER COLUMN gift_balance SET NOT NULL;

ALTER TABLE user_store_wallet ALTER COLUMN total_recharge_principal TYPE DECIMAL(18,2);

ALTER TABLE user_store_wallet ALTER COLUMN total_recharge_principal SET DEFAULT 0.00;

ALTER TABLE user_store_wallet ALTER COLUMN total_recharge_principal SET NOT NULL;

ALTER TABLE user_store_wallet ALTER COLUMN total_recharge_gift TYPE DECIMAL(18,2);

ALTER TABLE user_store_wallet ALTER COLUMN total_recharge_gift SET DEFAULT 0.00;

ALTER TABLE user_store_wallet ALTER COLUMN total_recharge_gift SET NOT NULL;

ALTER TABLE user_store_wallet ALTER COLUMN total_consume_principal TYPE DECIMAL(18,2);

ALTER TABLE user_store_wallet ALTER COLUMN total_consume_principal SET DEFAULT 0.00;

ALTER TABLE user_store_wallet ALTER COLUMN total_consume_principal SET NOT NULL;

ALTER TABLE user_store_wallet ALTER COLUMN total_consume_gift TYPE DECIMAL(18,2);

ALTER TABLE user_store_wallet ALTER COLUMN total_consume_gift SET DEFAULT 0.00;

ALTER TABLE user_store_wallet ALTER COLUMN total_consume_gift SET NOT NULL;

ALTER TABLE user_store_wallet ALTER COLUMN total_refund_principal TYPE DECIMAL(18,2);

ALTER TABLE user_store_wallet ALTER COLUMN total_refund_principal SET DEFAULT 0.00;

ALTER TABLE user_store_wallet ALTER COLUMN total_refund_principal SET NOT NULL;

ALTER TABLE wallet_transaction ALTER COLUMN amount TYPE DECIMAL(18,2);

ALTER TABLE wallet_transaction ALTER COLUMN amount SET NOT NULL;

ALTER TABLE wallet_transaction ALTER COLUMN balance_before TYPE DECIMAL(18,2);

ALTER TABLE wallet_transaction ALTER COLUMN balance_before SET NOT NULL;

ALTER TABLE wallet_transaction ALTER COLUMN balance_after TYPE DECIMAL(18,2);

ALTER TABLE wallet_transaction ALTER COLUMN balance_after SET NOT NULL;

ALTER TABLE recharge_order ALTER COLUMN principal_amount TYPE DECIMAL(18,2);

ALTER TABLE recharge_order ALTER COLUMN principal_amount SET DEFAULT 0.00;

ALTER TABLE recharge_order ALTER COLUMN principal_amount SET NOT NULL;

ALTER TABLE recharge_order ALTER COLUMN gift_amount TYPE DECIMAL(18,2);

ALTER TABLE recharge_order ALTER COLUMN gift_amount SET DEFAULT 0.00;

ALTER TABLE recharge_order ALTER COLUMN gift_amount SET NOT NULL;

ALTER TABLE recharge_order ALTER COLUMN pay_amount TYPE DECIMAL(18,2);

ALTER TABLE recharge_order ALTER COLUMN pay_amount SET DEFAULT 0.00;

ALTER TABLE recharge_order ALTER COLUMN pay_amount SET NOT NULL;

ALTER TABLE wash_order ALTER COLUMN estimated_amount TYPE DECIMAL(18,2);

ALTER TABLE wash_order ALTER COLUMN estimated_amount SET DEFAULT 0.00;

ALTER TABLE wash_order ALTER COLUMN estimated_amount SET NOT NULL;

ALTER TABLE wash_order ALTER COLUMN final_amount TYPE DECIMAL(18,2);

ALTER TABLE wash_order ALTER COLUMN final_amount SET DEFAULT 0.00;

ALTER TABLE wash_order ALTER COLUMN final_amount SET NOT NULL;

ALTER TABLE wash_order ALTER COLUMN paid_amount TYPE DECIMAL(18,2);

ALTER TABLE wash_order ALTER COLUMN paid_amount SET DEFAULT 0.00;

ALTER TABLE wash_order ALTER COLUMN paid_amount SET NOT NULL;

ALTER TABLE wash_order ALTER COLUMN refund_amount TYPE DECIMAL(18,2);

ALTER TABLE wash_order ALTER COLUMN refund_amount SET DEFAULT 0.00;

ALTER TABLE wash_order ALTER COLUMN refund_amount SET NOT NULL;

ALTER TABLE wash_order ALTER COLUMN first_period_discount_amount TYPE DECIMAL(18,2);

ALTER TABLE wash_order ALTER COLUMN first_period_discount_amount SET DEFAULT 0.00;

ALTER TABLE wash_order ALTER COLUMN first_period_discount_amount SET NOT NULL;

ALTER TABLE wash_order_payment_detail ALTER COLUMN amount TYPE DECIMAL(18,2);

ALTER TABLE wash_order_payment_detail ALTER COLUMN amount SET DEFAULT 0.00;

ALTER TABLE wash_order_payment_detail ALTER COLUMN amount SET NOT NULL;

ALTER TABLE wash_order_payment_detail ALTER COLUMN refunded_amount TYPE DECIMAL(18,2);

ALTER TABLE wash_order_payment_detail ALTER COLUMN refunded_amount SET DEFAULT 0.00;

ALTER TABLE wash_order_payment_detail ALTER COLUMN refunded_amount SET NOT NULL;

ALTER TABLE refund_order ALTER COLUMN refund_amount TYPE DECIMAL(18,2);

ALTER TABLE refund_order ALTER COLUMN refund_amount SET DEFAULT 0.00;

ALTER TABLE refund_order ALTER COLUMN refund_amount SET NOT NULL;

ALTER TABLE store_settlement_detail ALTER COLUMN principal_amount TYPE DECIMAL(18,2);

ALTER TABLE store_settlement_detail ALTER COLUMN principal_amount SET DEFAULT 0.00;

ALTER TABLE store_settlement_detail ALTER COLUMN principal_amount SET NOT NULL;

ALTER TABLE store_settlement_detail ALTER COLUMN refund_adjust_amount TYPE DECIMAL(18,2);

ALTER TABLE store_settlement_detail ALTER COLUMN refund_adjust_amount SET DEFAULT 0.00;

ALTER TABLE store_settlement_detail ALTER COLUMN refund_adjust_amount SET NOT NULL;

ALTER TABLE store_settlement_detail ALTER COLUMN net_amount TYPE DECIMAL(18,2);

ALTER TABLE store_settlement_detail ALTER COLUMN net_amount SET DEFAULT 0.00;

ALTER TABLE store_settlement_detail ALTER COLUMN net_amount SET NOT NULL;

CREATE TABLE IF NOT EXISTS payment_transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_no VARCHAR(64) NOT NULL,
  biz_type VARCHAR(30) NOT NULL,
  biz_order_id BIGINT DEFAULT NULL,
  biz_order_no VARCHAR(64) NOT NULL,
  user_id BIGINT DEFAULT NULL,
  store_id BIGINT DEFAULT NULL,
  pay_channel VARCHAR(30) NOT NULL,
  channel_trade_no VARCHAR(64) DEFAULT NULL,
  out_trade_no VARCHAR(64) DEFAULT NULL,
  pay_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  pay_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  currency_code VARCHAR(10) NOT NULL DEFAULT 'CNY',
  callback_count INT NOT NULL DEFAULT 0,
  request_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pay_time TIMESTAMP DEFAULT NULL,
  callback_time TIMESTAMP DEFAULT NULL,
  expire_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_payment_no UNIQUE (payment_no),
  CONSTRAINT uk_out_trade_no UNIQUE (out_trade_no)
);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_biz_order_no ON payment_transaction (biz_order_no);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_biz_type_status ON payment_transaction (biz_type, pay_status);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_user_id ON payment_transaction (user_id);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_store_id ON payment_transaction (store_id);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_pay_channel_status ON payment_transaction (pay_channel, pay_status);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_request_time ON payment_transaction (request_time);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_callback_time ON payment_transaction (callback_time);

CREATE TABLE IF NOT EXISTS payment_callback_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_transaction_id BIGINT DEFAULT NULL,
  payment_no VARCHAR(64) DEFAULT NULL,
  biz_order_no VARCHAR(64) DEFAULT NULL,
  pay_channel VARCHAR(30) NOT NULL,
  callback_type VARCHAR(30) NOT NULL DEFAULT 'payment_notify',
  channel_trade_no VARCHAR(64) DEFAULT NULL,
  notify_time TIMESTAMP DEFAULT NULL,
  sign_verified SMALLINT NOT NULL DEFAULT 0,
  process_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  process_result VARCHAR(255) DEFAULT NULL,
  raw_content TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_payment_transaction_id ON payment_callback_log (payment_transaction_id);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_payment_no ON payment_callback_log (payment_no);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_biz_order_no ON payment_callback_log (biz_order_no);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_pay_channel ON payment_callback_log (pay_channel);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_notify_time ON payment_callback_log (notify_time);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_process_status ON payment_callback_log (process_status);

CREATE TABLE IF NOT EXISTS refund_payment_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  refund_order_id BIGINT NOT NULL,
  refund_order_no VARCHAR(64) DEFAULT NULL,
  order_id BIGINT DEFAULT NULL,
  order_no VARCHAR(64) DEFAULT NULL,
  order_payment_detail_id BIGINT NOT NULL,
  source_type VARCHAR(20) NOT NULL,
  amount_type VARCHAR(20) DEFAULT NULL,
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  refund_times INT NOT NULL DEFAULT 0,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS refund_payment_detail__idx_refund_order_id ON refund_payment_detail (refund_order_id);

CREATE INDEX IF NOT EXISTS refund_payment_detail__idx_order_id ON refund_payment_detail (order_id);

CREATE INDEX IF NOT EXISTS refund_payment_detail__idx_order_payment_detail_id ON refund_payment_detail (order_payment_detail_id);

CREATE INDEX IF NOT EXISTS refund_payment_detail__idx_source_type ON refund_payment_detail (source_type);

CREATE TABLE IF NOT EXISTS device_event_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_id BIGINT NOT NULL,
  device_code VARCHAR(64) NOT NULL,
  event_type VARCHAR(30) NOT NULL,
  event_code VARCHAR(64) NOT NULL,
  event_time TIMESTAMP NOT NULL,
  order_id BIGINT DEFAULT NULL,
  order_no VARCHAR(64) DEFAULT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'info',
  payload TEXT DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS device_event_log__idx_device_id ON device_event_log (device_id);

CREATE INDEX IF NOT EXISTS device_event_log__idx_device_code ON device_event_log (device_code);

CREATE INDEX IF NOT EXISTS device_event_log__idx_event_time ON device_event_log (event_time);

CREATE INDEX IF NOT EXISTS device_event_log__idx_event_type ON device_event_log (event_type);

CREATE INDEX IF NOT EXISTS device_event_log__idx_order_id ON device_event_log (order_id);

CREATE INDEX IF NOT EXISTS device_event_log__idx_severity ON device_event_log (severity);

CREATE TABLE IF NOT EXISTS operation_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  operator_type VARCHAR(20) NOT NULL,
  operator_id BIGINT DEFAULT NULL,
  target_type VARCHAR(30) NOT NULL,
  target_id BIGINT NOT NULL,
  action_type VARCHAR(30) NOT NULL,
  change_summary VARCHAR(500) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS operation_audit_log__idx_operator ON operation_audit_log (operator_type, operator_id);

CREATE INDEX IF NOT EXISTS operation_audit_log__idx_target ON operation_audit_log (target_type, target_id);

CREATE INDEX IF NOT EXISTS operation_audit_log__idx_action_type ON operation_audit_log (action_type);

CREATE INDEX IF NOT EXISTS operation_audit_log__idx_created_at ON operation_audit_log (created_at);

ALTER TABLE wash_order ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid';

ALTER TABLE wash_order ADD COLUMN payment_status_desc VARCHAR(255) DEFAULT NULL;

ALTER TABLE wash_order ADD COLUMN refund_status_snapshot VARCHAR(20) NOT NULL DEFAULT 'none';

ALTER TABLE wash_order ADD COLUMN pricing_snapshot JSONB DEFAULT NULL;

ALTER TABLE wash_order ADD COLUMN pricing_snapshot_version INT NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS wash_order__idx_payment_status ON wash_order (payment_status);

CREATE INDEX IF NOT EXISTS wash_order__idx_refund_status_snapshot ON wash_order (refund_status_snapshot);

ALTER TABLE wash_order_payment_detail ADD COLUMN payment_seq INT NOT NULL DEFAULT 1;

ALTER TABLE wash_order_payment_detail ADD COLUMN settle_stage VARCHAR(20) NOT NULL DEFAULT 'final';

ALTER TABLE wash_order_payment_detail ADD COLUMN allocation_strategy VARCHAR(30) DEFAULT NULL;

ALTER TABLE wash_order_payment_detail ADD COLUMN biz_action_no VARCHAR(64) DEFAULT NULL;

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_order_payment_seq ON wash_order_payment_detail (order_id, payment_seq);

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_settle_stage ON wash_order_payment_detail (settle_stage);

CREATE INDEX IF NOT EXISTS wash_order_payment_detail__idx_biz_action_no ON wash_order_payment_detail (biz_action_no);

ALTER TABLE user_daily_discount_record ADD COLUMN discount_scope VARCHAR(30) NOT NULL DEFAULT 'user_day';

ALTER TABLE user_daily_discount_record ADD COLUMN scope_store_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE user_daily_discount_record DROP CONSTRAINT IF EXISTS uk_user_date_type;

ALTER TABLE user_daily_discount_record ADD CONSTRAINT uk_user_discount_scope UNIQUE (user_id, discount_date, discount_type, discount_scope, scope_store_id);

CREATE INDEX IF NOT EXISTS user_daily_discount_record__idx_discount_scope_store ON user_daily_discount_record (discount_scope, scope_store_id);

ALTER TABLE user_store_wallet ADD COLUMN available_principal_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00;

ALTER TABLE user_store_wallet ADD COLUMN frozen_principal_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00;

ALTER TABLE user_store_wallet ADD COLUMN available_gift_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00;

ALTER TABLE user_store_wallet ADD COLUMN frozen_gift_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00;

UPDATE user_store_wallet
SET
  available_principal_balance = principal_balance,
  available_gift_balance = gift_balance
WHERE available_principal_balance = 0.00
  AND frozen_principal_balance = 0.00
  AND available_gift_balance = 0.00
  AND frozen_gift_balance = 0.00;

CREATE INDEX IF NOT EXISTS user_store_wallet__idx_user_store_wallet_available_principal ON user_store_wallet (available_principal_balance);

CREATE INDEX IF NOT EXISTS user_store_wallet__idx_user_store_wallet_available_gift ON user_store_wallet (available_gift_balance);

ALTER TABLE wallet_transaction ADD COLUMN balance_bucket VARCHAR(20) NOT NULL DEFAULT 'available';

ALTER TABLE wallet_transaction ADD COLUMN freeze_type VARCHAR(20) DEFAULT NULL;

ALTER TABLE wallet_transaction ADD COLUMN related_action VARCHAR(30) DEFAULT NULL;

ALTER TABLE wallet_transaction ADD COLUMN biz_action_no VARCHAR(64) DEFAULT NULL;

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_balance_bucket ON wallet_transaction (balance_bucket);

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_related_action ON wallet_transaction (related_action);

CREATE INDEX IF NOT EXISTS wallet_transaction__idx_wallet_biz_action_no ON wallet_transaction (biz_action_no);

ALTER TABLE payment_transaction ADD COLUMN request_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE payment_transaction ADD COLUMN biz_action_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE payment_transaction ADD COLUMN idempotency_key VARCHAR(64) DEFAULT NULL;

ALTER TABLE payment_transaction ADD CONSTRAINT uk_payment_request_no UNIQUE (request_no);

ALTER TABLE payment_transaction ADD CONSTRAINT uk_payment_idempotency_key UNIQUE (idempotency_key);

CREATE INDEX IF NOT EXISTS payment_transaction__idx_payment_biz_action_no ON payment_transaction (biz_action_no);

ALTER TABLE payment_callback_log ADD COLUMN callback_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE payment_callback_log ADD COLUMN idempotency_key VARCHAR(64) DEFAULT NULL;

ALTER TABLE payment_callback_log ADD COLUMN archive_flag SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE payment_callback_log ADD COLUMN archive_batch_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE payment_callback_log ADD COLUMN archived_at TIMESTAMP DEFAULT NULL;

ALTER TABLE payment_callback_log ADD CONSTRAINT uk_payment_callback_no UNIQUE (callback_no);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_payment_callback_idempotency_key ON payment_callback_log (idempotency_key);

CREATE INDEX IF NOT EXISTS payment_callback_log__idx_payment_callback_archive_created ON payment_callback_log (archive_flag, created_at);

ALTER TABLE refund_order ADD COLUMN refund_channel VARCHAR(30) DEFAULT NULL;

ALTER TABLE refund_order ADD COLUMN external_refund_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE refund_order ADD COLUMN external_refund_status VARCHAR(20) NOT NULL DEFAULT 'pending';

ALTER TABLE refund_order ADD COLUMN callback_status VARCHAR(20) NOT NULL DEFAULT 'none';

ALTER TABLE refund_order ADD COLUMN callback_time TIMESTAMP DEFAULT NULL;

ALTER TABLE refund_order ADD COLUMN retry_times INT NOT NULL DEFAULT 0;

ALTER TABLE refund_order ADD COLUMN fail_reason VARCHAR(255) DEFAULT NULL;

ALTER TABLE refund_order ADD COLUMN request_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE refund_order ADD COLUMN biz_action_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE refund_order ADD COLUMN idempotency_key VARCHAR(64) DEFAULT NULL;

ALTER TABLE refund_order ADD CONSTRAINT uk_refund_external_refund_no UNIQUE (external_refund_no);

ALTER TABLE refund_order ADD CONSTRAINT uk_refund_request_no UNIQUE (request_no);

ALTER TABLE refund_order ADD CONSTRAINT uk_refund_idempotency_key UNIQUE (idempotency_key);

CREATE INDEX IF NOT EXISTS refund_order__idx_refund_external_status ON refund_order (external_refund_status);

CREATE INDEX IF NOT EXISTS refund_order__idx_refund_callback_status ON refund_order (callback_status);

CREATE INDEX IF NOT EXISTS refund_order__idx_refund_biz_action_no ON refund_order (biz_action_no);

ALTER TABLE device_command_log ADD COLUMN request_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE device_command_log ADD COLUMN biz_action_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE device_command_log ADD COLUMN idempotency_key VARCHAR(64) DEFAULT NULL;

ALTER TABLE device_command_log ADD CONSTRAINT uk_device_command_request_no UNIQUE (request_no);

ALTER TABLE device_command_log ADD CONSTRAINT uk_device_command_idempotency_key UNIQUE (idempotency_key);

CREATE INDEX IF NOT EXISTS device_command_log__idx_device_command_biz_action_no ON device_command_log (biz_action_no);

ALTER TABLE device ADD COLUMN device_role VARCHAR(20) NOT NULL DEFAULT 'main';

ALTER TABLE device ADD COLUMN bay_device_type VARCHAR(30) DEFAULT NULL;

CREATE INDEX IF NOT EXISTS device__idx_bay_role_type ON device (bay_id, device_role, bay_device_type);

CREATE TABLE IF NOT EXISTS store_settlement_bill (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bill_no VARCHAR(64) NOT NULL,
  from_store_id BIGINT NOT NULL,
  to_store_id BIGINT NOT NULL,
  settlement_period_type VARCHAR(20) NOT NULL DEFAULT 'day',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_order_count INT NOT NULL DEFAULT 0,
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  total_refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  settlement_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  lock_status VARCHAR(20) NOT NULL DEFAULT 'unlocked',
  locked_at TIMESTAMP DEFAULT NULL,
  confirmed_at TIMESTAMP DEFAULT NULL,
  paid_at TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_store_settlement_bill_no UNIQUE (bill_no),
  CONSTRAINT uk_store_settlement_period UNIQUE (from_store_id, to_store_id, settlement_period_type, start_date, end_date)
);

CREATE INDEX IF NOT EXISTS store_settlement_bill__idx_bill_from_store ON store_settlement_bill (from_store_id);

CREATE INDEX IF NOT EXISTS store_settlement_bill__idx_bill_to_store ON store_settlement_bill (to_store_id);

CREATE INDEX IF NOT EXISTS store_settlement_bill__idx_bill_status ON store_settlement_bill (settlement_status);

CREATE INDEX IF NOT EXISTS store_settlement_bill__idx_bill_lock_status ON store_settlement_bill (lock_status);

CREATE INDEX IF NOT EXISTS store_settlement_bill__idx_bill_period ON store_settlement_bill (settlement_period_type, start_date, end_date);

ALTER TABLE store_settlement_detail ADD COLUMN bill_id BIGINT DEFAULT NULL;

ALTER TABLE store_settlement_detail ADD COLUMN bill_no VARCHAR(64) DEFAULT NULL;

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_bill_id ON store_settlement_detail (bill_id);

CREATE INDEX IF NOT EXISTS store_settlement_detail__idx_bill_no ON store_settlement_detail (bill_no);

ALTER TABLE device_heartbeat_log ADD COLUMN archive_flag SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE device_heartbeat_log ADD COLUMN archive_batch_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE device_heartbeat_log ADD COLUMN archived_at TIMESTAMP DEFAULT NULL;

CREATE INDEX IF NOT EXISTS device_heartbeat_log__idx_device_heartbeat_archive_created ON device_heartbeat_log (archive_flag, created_at);

ALTER TABLE device_event_log ADD COLUMN archive_flag SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE device_event_log ADD COLUMN archive_batch_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE device_event_log ADD COLUMN archived_at TIMESTAMP DEFAULT NULL;

CREATE INDEX IF NOT EXISTS device_event_log__idx_device_event_archive_created ON device_event_log (archive_flag, created_at);

ALTER TABLE operation_audit_log ADD COLUMN archive_flag SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE operation_audit_log ADD COLUMN archive_batch_no VARCHAR(64) DEFAULT NULL;

ALTER TABLE operation_audit_log ADD COLUMN archived_at TIMESTAMP DEFAULT NULL;

CREATE INDEX IF NOT EXISTS operation_audit_log__idx_operation_audit_archive_created ON operation_audit_log (archive_flag, created_at);

ALTER TABLE payment_transaction ADD COLUMN prepay_id VARCHAR(128) DEFAULT NULL;

ALTER TABLE payment_transaction ADD COLUMN fail_reason VARCHAR(255) DEFAULT NULL;

ALTER TABLE wallet_transaction ADD CONSTRAINT uk_wallet_recharge_action_amount_type UNIQUE (biz_action_no, amount_type);

CREATE TABLE IF NOT EXISTS wallet_recharge_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  store_id BIGINT NOT NULL,
  product_name VARCHAR(100) NOT NULL,
  pay_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  principal_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  gift_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  effective_time TIMESTAMP DEFAULT NULL,
  expire_time TIMESTAMP DEFAULT NULL,
  purchase_limit INT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS wallet_recharge_product__idx_store_id ON wallet_recharge_product (store_id);

CREATE INDEX IF NOT EXISTS wallet_recharge_product__idx_status ON wallet_recharge_product (status);

CREATE INDEX IF NOT EXISTS wallet_recharge_product__idx_effective_expire ON wallet_recharge_product (effective_time, expire_time);

ALTER TABLE recharge_order ADD COLUMN recharge_product_id BIGINT DEFAULT NULL;

CREATE INDEX IF NOT EXISTS recharge_order__idx_recharge_product_id ON recharge_order (recharge_product_id);

CREATE TABLE IF NOT EXISTS franchisee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  franchisee_code VARCHAR(64) NOT NULL,
  franchisee_name VARCHAR(120) NOT NULL,
  contact_name VARCHAR(80) DEFAULT NULL,
  contact_phone VARCHAR(30) DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_franchisee_code UNIQUE (franchisee_code)
);

CREATE INDEX IF NOT EXISTS franchisee__idx_franchisee_status ON franchisee (status);

INSERT INTO franchisee (id, franchisee_code, franchisee_name, status, remark)
VALUES (1, 'DIRECT', '直营总部', 1, 'Default direct tenant')
ON CONFLICT (id) DO UPDATE SET
  franchisee_name = '直营总部',
  status = 1;

ALTER TABLE store ADD COLUMN franchisee_id BIGINT NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS store__idx_store_franchisee ON store (franchisee_id);

CREATE TABLE IF NOT EXISTS mini_admin_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  franchisee_id BIGINT NOT NULL DEFAULT 1,
  openid VARCHAR(128) NOT NULL,
  staff_no VARCHAR(64) NOT NULL,
  staff_name VARCHAR(80) NOT NULL,
  mobile VARCHAR(30) DEFAULT NULL,
  role_code VARCHAR(40) NOT NULL DEFAULT 'store_staff',
  data_scope VARCHAR(30) NOT NULL DEFAULT 'store',
  status SMALLINT NOT NULL DEFAULT 1,
  last_login_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_mini_admin_openid UNIQUE (openid),
  CONSTRAINT uk_mini_admin_staff_no UNIQUE (staff_no)
);

CREATE INDEX IF NOT EXISTS mini_admin_staff__idx_mini_admin_franchisee ON mini_admin_staff (franchisee_id);

CREATE INDEX IF NOT EXISTS mini_admin_staff__idx_mini_admin_role ON mini_admin_staff (role_code);

CREATE INDEX IF NOT EXISTS mini_admin_staff__idx_mini_admin_status ON mini_admin_staff (status);

CREATE TABLE IF NOT EXISTS mini_admin_staff_store (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  staff_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  is_primary SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_staff_store UNIQUE (staff_id, store_id)
);

CREATE INDEX IF NOT EXISTS mini_admin_staff_store__idx_staff_store_staff ON mini_admin_staff_store (staff_id);

CREATE INDEX IF NOT EXISTS mini_admin_staff_store__idx_staff_store_store ON mini_admin_staff_store (store_id);

CREATE TABLE IF NOT EXISTS mini_admin_staff_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  staff_id BIGINT NOT NULL,
  openid VARCHAR(128) NOT NULL,
  token VARCHAR(96) NOT NULL,
  expire_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_mini_admin_session_token UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS mini_admin_staff_session__idx_mini_admin_session_staff ON mini_admin_staff_session (staff_id);

CREATE INDEX IF NOT EXISTS mini_admin_staff_session__idx_mini_admin_session_expire ON mini_admin_staff_session (expire_time);

INSERT INTO mini_admin_staff (
  id,
  franchisee_id,
  openid,
  staff_no,
  staff_name,
  role_code,
  data_scope,
  status,
  remark
)
VALUES (
  1,
  1,
  'mock_openid_local',
  'A000001',
  '本地测试店长',
  'store_manager',
  'store',
  1,
  'Seed store manager account for local mini-admin login when WeChat credentials are not configured'
)
ON CONFLICT (id) DO UPDATE SET
  staff_name = '本地测试店长',
  role_code = 'store_manager',
  data_scope = 'store',
  status = 1;

INSERT INTO mini_admin_staff_store (staff_id, store_id, is_primary, created_at)
SELECT 1, s.id, 1, CURRENT_TIMESTAMP
FROM store s
WHERE s.id = (SELECT MIN(id) FROM store)
  AND NOT EXISTS (
    SELECT 1
    FROM mini_admin_staff_store ss
    WHERE ss.staff_id = 1
      AND ss.store_id = s.id
  );

UPDATE mini_admin_staff_store AS ss SET is_primary = 1 FROM store AS s WHERE s.id = ss.store_id AND ss.staff_id = 1 AND s.id = (SELECT MIN(id) FROM store);

INSERT INTO mini_admin_staff (
  id, franchisee_id, openid, staff_no, staff_name, role_code, data_scope, status, remark
)
VALUES (
  101, 1, 'mock_openid_platform', 'A_PLATFORM', '总部测试管理员', 'platform_admin', 'platform', 1, 'Local demo platform admin'
)
ON CONFLICT (id) DO UPDATE SET
  staff_name = '总部测试管理员',
  role_code = 'platform_admin',
  data_scope = 'platform',
  status = 1;

INSERT INTO mini_admin_staff (
  id, franchisee_id, openid, staff_no, staff_name, role_code, data_scope, status, remark
)
VALUES (
  102, 1, 'mock_openid_franchisee', 'A_FRANCHISEE', '加盟老板演示号', 'franchisee_owner', 'franchisee', 1, 'Local demo franchisee owner'
)
ON CONFLICT (id) DO UPDATE SET
  staff_name = '加盟老板演示号',
  role_code = 'franchisee_owner',
  data_scope = 'franchisee',
  franchisee_id = 1,
  status = 1;

INSERT INTO mini_admin_staff (
  id, franchisee_id, openid, staff_no, staff_name, role_code, data_scope, status, remark
)
VALUES (
  103, 1, 'mock_openid_store', 'A_STORE', '门店一店长演示号', 'store_manager', 'store', 1, 'Local demo store manager'
)
ON CONFLICT (id) DO UPDATE SET
  staff_name = '门店一店长演示号',
  role_code = 'store_manager',
  data_scope = 'store',
  franchisee_id = 1,
  status = 1;

INSERT INTO mini_admin_staff_store (staff_id, store_id, is_primary, created_at)
SELECT 103, s.id, 1, CURRENT_TIMESTAMP
FROM store s
WHERE s.id = (SELECT MIN(id) FROM store)
  AND NOT EXISTS (
    SELECT 1
    FROM mini_admin_staff_store ss
    WHERE ss.staff_id = 103
      AND ss.store_id = s.id
  );

CREATE TABLE IF NOT EXISTS mini_admin_asset_operation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  operation_no VARCHAR(64) NOT NULL,
  operation_type VARCHAR(40) NOT NULL,
  change_type VARCHAR(20) DEFAULT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  wallet_id BIGINT DEFAULT NULL,
  user_card_id BIGINT DEFAULT NULL,
  amount_type VARCHAR(20) DEFAULT NULL,
  principal_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  gift_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  card_delta_times INT NOT NULL DEFAULT 0,
  operator_staff_id BIGINT NOT NULL,
  operator_role_code VARCHAR(40) DEFAULT NULL,
  remark VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_asset_operation_no UNIQUE (operation_no)
);

CREATE INDEX IF NOT EXISTS mini_admin_asset_operation__idx_asset_operation_user ON mini_admin_asset_operation (user_id, created_at);

CREATE INDEX IF NOT EXISTS mini_admin_asset_operation__idx_asset_operation_store ON mini_admin_asset_operation (store_id, created_at);

CREATE INDEX IF NOT EXISTS mini_admin_asset_operation__idx_asset_operation_type ON mini_admin_asset_operation (operation_type, created_at);

CREATE INDEX IF NOT EXISTS mini_admin_asset_operation__idx_asset_operation_operator ON mini_admin_asset_operation (operator_staff_id, created_at);

INSERT INTO mini_admin_staff (
  id,
  franchisee_id,
  openid,
  staff_no,
  staff_name,
  mobile,
  role_code,
  data_scope,
  status,
  remark
) VALUES (
  104,
  1,
  'mock_openid_staff',
  'STAFF_STORE_1_DEMO',
  '门店一员工演示号',
  '',
  'store_staff',
  'store',
  1,
  'local demo store staff'
)
ON CONFLICT (id) DO UPDATE SET
  franchisee_id = EXCLUDED.franchisee_id,
  openid = EXCLUDED.openid,
  staff_name = EXCLUDED.staff_name,
  role_code = EXCLUDED.role_code,
  data_scope = EXCLUDED.data_scope,
  status = EXCLUDED.status,
  remark = EXCLUDED.remark;

INSERT INTO mini_admin_staff_store (
  staff_id,
  store_id,
  is_primary,
  created_at
) VALUES (
  104,
  1,
  1,
  CURRENT_TIMESTAMP
)
ON CONFLICT (staff_id, store_id) DO UPDATE SET
  is_primary = EXCLUDED.is_primary;

ALTER TABLE store ADD COLUMN feature_tags VARCHAR(255) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS wash_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  queue_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  queue_status VARCHAR(20) NOT NULL DEFAULT 'waiting',
  user_latitude DECIMAL(10,6) DEFAULT NULL,
  user_longitude DECIMAL(10,6) DEFAULT NULL,
  distance_km DECIMAL(10,3) DEFAULT NULL,
  cancel_reason VARCHAR(120) DEFAULT NULL,
  queued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cancelled_at TIMESTAMP DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_queue_no UNIQUE (queue_no)
);

CREATE INDEX IF NOT EXISTS wash_queue__idx_queue_store_status ON wash_queue (store_id, queue_status, id);

CREATE INDEX IF NOT EXISTS wash_queue__idx_queue_user_store_status ON wash_queue (user_id, store_id, queue_status, id);

CREATE TABLE IF NOT EXISTS franchise_contact (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  contact_name VARCHAR(50) NOT NULL,
  contact_phone VARCHAR(30) NOT NULL,
  source VARCHAR(50) DEFAULT 'miniapp',
  remark VARCHAR(500) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS franchise_contact__idx_franchise_contact_phone ON franchise_contact (contact_phone);

CREATE INDEX IF NOT EXISTS franchise_contact__idx_franchise_contact_created_at ON franchise_contact (created_at);

ALTER TABLE user_info ADD COLUMN points INT NOT NULL DEFAULT 0;

ALTER TABLE user_info ADD COLUMN member_expire_time TIMESTAMP DEFAULT NULL;

CREATE TABLE IF NOT EXISTS membership_setting (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  setting_key VARCHAR(40) NOT NULL,
  member_day_enabled SMALLINT NOT NULL DEFAULT 1,
  member_day_weekday SMALLINT NOT NULL DEFAULT 3,
  member_day_start_time TIME NOT NULL DEFAULT '00:00:00',
  member_day_end_time TIME NOT NULL DEFAULT '23:59:59',
  member_day_first_minutes INT NOT NULL DEFAULT 10,
  member_day_discount_rate DECIMAL(5,4) NOT NULL DEFAULT 0.7500,
  benefit_text VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_membership_setting_key UNIQUE (setting_key)
);

CREATE TABLE IF NOT EXISTS membership_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  plan_code VARCHAR(40) NOT NULL,
  plan_name VARCHAR(100) NOT NULL,
  plan_type VARCHAR(20) NOT NULL,
  duration_months INT NOT NULL,
  price DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  benefit_text VARCHAR(255) DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_membership_plan_code UNIQUE (plan_code)
);

CREATE INDEX IF NOT EXISTS membership_plan__idx_membership_plan_status ON membership_plan (status);

CREATE TABLE IF NOT EXISTS membership_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  pay_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  pay_channel VARCHAR(30) DEFAULT NULL,
  pay_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  payment_no VARCHAR(64) DEFAULT NULL,
  third_party_trade_no VARCHAR(64) DEFAULT NULL,
  pay_time TIMESTAMP DEFAULT NULL,
  member_start_time TIMESTAMP DEFAULT NULL,
  member_expire_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_membership_order_no UNIQUE (order_no)
);

CREATE INDEX IF NOT EXISTS membership_order__idx_membership_order_user ON membership_order (user_id);

CREATE INDEX IF NOT EXISTS membership_order__idx_membership_order_status ON membership_order (pay_status);

CREATE TABLE IF NOT EXISTS point_mall_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  cover_image VARCHAR(500) DEFAULT NULL,
  product_type VARCHAR(20) NOT NULL DEFAULT 'wash_service',
  points_price INT NOT NULL,
  stock_total INT NOT NULL DEFAULT 0,
  limit_per_user INT NOT NULL DEFAULT 0,
  effective_time TIMESTAMP DEFAULT NULL,
  expire_time TIMESTAMP DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS point_mall_product__idx_point_mall_product_status ON point_mall_product (status);

CREATE INDEX IF NOT EXISTS point_mall_product__idx_point_mall_product_available ON point_mall_product (effective_time, expire_time);

CREATE TABLE IF NOT EXISTS point_redemption_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  redemption_no VARCHAR(64) NOT NULL,
  request_no VARCHAR(64) DEFAULT NULL,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  product_title_snapshot VARCHAR(100) NOT NULL,
  points_amount INT NOT NULL,
  fulfillment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  fulfillment_reference VARCHAR(128) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_point_redemption_no UNIQUE (redemption_no),
  CONSTRAINT uk_point_redemption_user_request UNIQUE (user_id, request_no)
);

CREATE INDEX IF NOT EXISTS point_redemption_order__idx_point_redemption_user_created ON point_redemption_order (user_id, created_at);

CREATE INDEX IF NOT EXISTS point_redemption_order__idx_point_redemption_product ON point_redemption_order (product_id);

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  target_table text;
BEGIN
  FOR target_table IN
    SELECT DISTINCT columns.table_name
    FROM information_schema.columns AS columns
    WHERE columns.table_schema = current_schema() AND columns.column_name = 'updated_at'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_updated_at ON %I', target_table, target_table);
    EXECUTE format(
      'CREATE TRIGGER trg_%s_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      target_table,
      target_table
    );
  END LOOP;
END;
$$;

DO $$
DECLARE
  target_table text;
BEGIN
  FOR target_table IN
    SELECT DISTINCT columns.table_name
    FROM information_schema.columns AS columns
    WHERE columns.table_schema = current_schema() AND columns.column_name = 'id'
  LOOP
    EXECUTE format(
      'SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE((SELECT MAX(id) FROM %I), 1), true)',
      target_table,
      'id',
      target_table
    );
  END LOOP;
END;
$$;
