CREATE TABLE IF NOT EXISTS ranking_display_adjustment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  scope VARCHAR(20) NOT NULL DEFAULT 'total',
  display_duration_seconds BIGINT NOT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  occurred_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ranking_display_adjustment__idx_occurred_at
  ON ranking_display_adjustment (occurred_at);

CREATE INDEX IF NOT EXISTS ranking_display_adjustment__idx_user_occurred_at
  ON ranking_display_adjustment (user_id, occurred_at);

CREATE INDEX IF NOT EXISTS ranking_display_adjustment__idx_scope_occurred_at
  ON ranking_display_adjustment (scope, occurred_at);

CREATE INDEX IF NOT EXISTS ranking_display_adjustment__idx_scope_user_occurred_at
  ON ranking_display_adjustment (scope, user_id, occurred_at);
