CREATE TABLE IF NOT EXISTS store_exchange_voucher (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  batch_no VARCHAR(64) NOT NULL,
  serial_no VARCHAR(64) NOT NULL,
  store_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(20) NOT NULL DEFAULT 'unused',
  redeemed_user_id BIGINT DEFAULT NULL,
  redeemed_wallet_transaction_id BIGINT DEFAULT NULL,
  created_by_staff_id BIGINT DEFAULT NULL,
  created_by_role_code VARCHAR(40) DEFAULT NULL,
  redeemed_at TIMESTAMP DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_store_exchange_voucher_serial UNIQUE (serial_no)
);

CREATE INDEX IF NOT EXISTS store_exchange_voucher__idx_batch ON store_exchange_voucher (batch_no);
CREATE INDEX IF NOT EXISTS store_exchange_voucher__idx_store_status ON store_exchange_voucher (store_id, status, created_at);
CREATE INDEX IF NOT EXISTS store_exchange_voucher__idx_redeemed_user ON store_exchange_voucher (redeemed_user_id, redeemed_at);
CREATE INDEX IF NOT EXISTS store_exchange_voucher__idx_transaction ON store_exchange_voucher (redeemed_wallet_transaction_id);

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_store_exchange_voucher_updated_at ON store_exchange_voucher;
CREATE TRIGGER trg_store_exchange_voucher_updated_at
BEFORE UPDATE ON store_exchange_voucher
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
